# Generated by Django 4.2.7 on 2023-11-27 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseData', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaseData',
            new_name='BaseDataAPI',
        ),
    ]
