# Generated by Django 4.2.7 on 2023-12-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TariffData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=40)),
                ('b_charge', models.IntegerField()),
                ('add_wt', models.IntegerField()),
                ('add_liability', models.FloatField()),
                ('bill_entry', models.IntegerField()),
                ('cust_inspection', models.IntegerField()),
                ('kp_charge', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TariffEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=40)),
                ('load_plan', models.CharField(choices=[('CONSOLE', 'console'), ('SINGLE', 'single')], default='CONSOLE', max_length=10)),
                ('destination', models.CharField(choices=[('ANR', 'ANR'), ('BOM', 'BOM'), ('SUR', 'SUR'), ('JFK', 'JFK'), ('SPZ', 'SPZ'), ('BRU', 'BRU'), ('BKK', 'BKK'), ('LHR', 'LHR'), ('SIN', 'SIN'), ('HKG', 'HKG')], max_length=10)),
                ('value', models.FloatField()),
                ('wt', models.IntegerField()),
                ('commodity', models.CharField(choices=[('RD', 'RD'), ('PD', 'PD'), ('JEW', 'JEW'), ('others', 'OTHERS')], max_length=10)),
                ('VAT_claim', models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], max_length=3)),
            ],
        ),
    ]
